version: "3.8"
services:
  web:
    build: .
    container_name: yt2mp3
    ports:
      - "5000:5000"
    env_file:
      - .env        # optional, for FLASK_SECRET
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app
    volumes:
      - ./mp3s:/app/mp3s
      - ./mp4s:/app/mp4s
      - ./cookies.txt:/app/cookies.txt:ro
